#! /bin/sh

[ $(id --user) != 0 ] && echo "Please running script as root." && exit

_PROPERTIES="$(dirname $0)/zram.properties"

[ -f "$_PROPERTIES" ] && . "$_PROPERTIES"

NUM_DEVICES_DEFAULT=1

NUM_DEVICES="${NUM_DEVICES:-$NUM_DEVICES_DEFAULT}"

[ $NUM_DEVICES -lt $NUM_DEVICES_DEFAULT ] && NUM_DEVICES=$NUM_DEVICES_DEFAULT

modprobe zram --verbose num_devices=$NUM_DEVICES

for i in $(seq 0 $(($NUM_DEVICES - 1))); do
    echo ${COMP_ALGORITHM:-zstd} > /sys/block/zram$i/comp_algorithm
    echo ${DISK_SIZE:-1024M} > /sys/block/zram$i/disksize
    mkswap /dev/zram$i
    swapon -p ${PRIORITY:-75} /dev/zram$i
done

sysctl -w vm.swappiness=${SWAPPINESS:-10}
sysctl -p
